steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['install']

  # Build the application
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']

  # Build and push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$_PROJECT_ID/$_SERVICE_NAME',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$_PROJECT_ID/$_SERVICE_NAME']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - 'gcr.io/$_PROJECT_ID/$_SERVICE_NAME'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

# Store images in Container Registry
images:
  - 'gcr.io/$_PROJECT_ID/$_SERVICE_NAME'

# Substitutions with default values
substitutions:
  _PROJECT_ID: 'api-for-warp-drive'
  _REGION: 'us-west1'
  _SERVICE_NAME: 'aixtiv-frontend'

